// ============================================================================
// Auth Tables — generated by better-auth CLI (do not hand-edit)
// Run: pnpm dlx @better-auth/cli generate --output src/db/auth-schema.ts
//
// TODO: Uncomment the line below after running the CLI (see README step 6).
// ============================================================================

// export * from './auth-schema';

// ============================================================================
// App Tables — add your tables here
// ============================================================================
