// ============================================================================
// Auth Tables — generated by better-auth CLI (do not hand-edit)
// Run: pnpm dlx @better-auth/cli generate --output src/db/auth-schema.ts
// ============================================================================

export * from './auth-schema';

// ============================================================================
// App Tables
// ============================================================================

import { relations } from 'drizzle-orm';
import {
  pgTable,
  text,
  timestamp,
  boolean,
  uuid,
  integer,
  date,
  index,
} from 'drizzle-orm/pg-core';
import { user } from './auth-schema';

export const todos = pgTable(
  'todos',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    title: text('title').notNull(),
    completed: boolean('completed').default(false).notNull(),
    isToday: boolean('is_today').default(false).notNull(),
    dueDate: date('due_date'),
    sortOrder: integer('sort_order').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('todos_userId_sortOrder_idx').on(table.userId, table.sortOrder)],
);

export const todosRelations = relations(todos, ({ one }) => ({
  user: one(user, {
    fields: [todos.userId],
    references: [user.id],
  }),
}));
